import time
talk=input("I'm sorry to hear that. Do you want to talk about it? (Y/N): ")    
if talk.lower() == 'n':
    
    print("Ok but practice some breathing exercises with me.")
    while True:    
        print("Inhale")
        time.sleep(3)
        print("exhale")
        time.sleep(3)
        print("Inhale")
        time.sleep(3)
        print("exhale")
        time.sleep(3)
        print("Inhale")
        time.sleep(3)
        print("exhale")
        time.sleep(3)
        print("Inhale")
        time.sleep(3)
        print("exhale")
        time.sleep(3)
        print("Inhale")
        time.sleep(3)
        print("exhale")
        time.sleep(3)
        print("Inhale")
        time.sleep(3)
        print("exhale")
        time.sleep(3)
        print("Inhale")
        time.sleep(3)
        print("exhale")
        if input("Do you want to continue breathing exercises? ").lower() == "n":
            break